she_codes_news/news/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    # path('add-story/', login_required(views.AddStoryView.as_view()), name='newStory'),
    path('add-story/',(views.AddStoryView.as_view()), name='newStory'),
    path('<int:pk>/comment', views.AddCommentView.as_view(), name='addComment'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),

]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, AccountView

app_name ='users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('profile', AccountView.as_view(), name='profile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    pub_date = models.DateTimeField()
    content = models.TextField()
    image = models.URLField(null=True, blank=True)

class Comment(models.Model):
    story = models.ForeignKey(
        NewsStory,
        related_name="comments",
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )  
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)  

she_codes_news/users/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory
from .models import Comment
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class StoryForm(ModelForm):
    class Meta:

            model = NewsStory        
            fields = ['title', 'pub_date', 'content', 'image']
            labels = {'title':'', 
                      'pub_date':'', 
                      'content':'',
                      'image':''}
            widgets = {
                'title':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Story Title'}), 
                'pub_date': forms.DateTimeInput(
                    format=['%d/%m/%Y %H:%M'],
                    attrs={
                        'class': 'form-control',
                        'placeholder':'Select date and time to publish story',
                        'type': 'datetime-local'}),
                'content':forms.Textarea(attrs={'class':'form-control','placeholder':'Write your story here....'}),
                'image':forms.URLInput(attrs={'class':'form-control','placeholder':'Image URL'}),
}
            
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:        
        model = CustomUser        
        fields = ['username', 'email']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:        
        model = CustomUser        
        fields = ['username', 'email']

she_codes_news/news/views.py
from typing import Any
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory, Comment
from .forms import StoryForm
from .forms import CommentForm
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from users.models import CustomUser


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        # context for 'other_stories' that are not in the 'latest_stories' to be used on index.html so that stories are not shown twice
        context['other_stories'] = NewsStory.objects.all().order_by('-pub_date')[4:]
        return context

class AuthorView(generic.DetailView):
    model = CustomUser
    template_name = 'news/author.html'
    context_object_name = "author"

    def get_object(self, *args, **kwargs):
        return CustomUser.objects.get(pk=self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_latest_stories'] = NewsStory.objects.filter(author_id=self.kwargs['pk']).order_by('-pub_date')[:4]
        context['author_other_stories'] = NewsStory.objects.filter(author_id=self.kwargs['pk']).order_by('-pub_date')[4:]
        context['author'] = CustomUser.objects.get(id=self.kwargs['pk'])
        context['author_comments'] = Comment.objects.filter(author_id=self.kwargs['pk']).order_by('-date')
        return context    
    
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form']= CommentForm()
        return context

class AddStoryView(LoginRequiredMixin, generic.CreateView):
    login_url = 'login'
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class AddCommentView(generic.CreateView):
    
    form_class = CommentForm

    def get(self, request, *args, **kwargs):
        return redirect("news:story", pk=self.kwargs.get("pk"))

    def form_valid(self, form):
        form.instance.author = self.request.user
        pk = self.kwargs.get("pk")
        form.instance.story = get_object_or_404(NewsStory, pk=pk)
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('news:story',kwargs=
        {'pk':self.kwargs.get("pk")})
                   

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from news.models import NewsStory, Comment
from .models import CustomUser
from .forms import CustomUserCreationForm


class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'


class AccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    context_object_name = 'profile'

    def get_object(self, *args, **kwargs):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_stories'] = NewsStory.objects.filter(author=self.request.user).order_by('-pub_date')
        # USING PK
        # context['user_comments'] = Comment.objects.filter(author=self.kwargs['pk']).order_by('-date')
        context['user_comments'] = Comment.objects.filter(author=self.request.user).order_by('-date')
        return context
    

she_codes_news/news/templates/news/author.html
{% extends 'base.html' %}
{% load static %} 
{% block stylesheets %}
<link rel="stylesheet" type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}
<br>

<h2>Latest News from {{ author }}</h2>

<div id="author_latest_stories">
    {% if author_latest_stories %}
        {% for story in author_latest_stories %}
            {% include './storyCard.html' with story=story position=forloop.counter %}
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>
<br>
<h2>{{ author }}'s Other News Stories</h2>

<div id="author_other_stories">
    {% if author_other_stories %}
        {% for story in author_other_stories %}
            {% include "./storyCard.html" with story=story %}
            <!-- <p>{{ story.title }}</p> -->
        {% endfor %}
    {% else %}
        <p>No stories are available.</p>
    {% endif %}
</div>
<br>
<!-- AUTHOR COMMENTS SECTION -->
<h2>{{ author }}'s Comments</h2>
  <div id="author_comments">
    {% if author_comments %}
        {% for comments in author_comments %}
    <div class="story_comment">
        <div class = "comment_bubble" >
            <span id="comment_text" class="emphasized"> {{ comments.text }} </span>       
            <h6 id = "comment_date"> - {{ comments.date }}</h6> 
            <a id = "story_title" href="{%url 'news:story' comments.story.id %}"> 
                <h5>{{comments.story.title}}</h5>
                <h6>{{comments.story.author}}</h6>
             </a>
        </div>
    </div>
            {% endfor %}
    {% else %}
        <p>No comments for {{ author }} yet.</p>
    {% endif %}


{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html"%}
{% load crispy_forms_tags %} 
{% block content %} 
<h2>Submit New Story</h2>
<form id = "story_form" action="" method="post">
        {% csrf_token %}
            {{ form | crispy }}

        <input id ="submit" type="submit" value="Submit">
    </form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends 'base.html' %}
{% load static %} 
{% block stylesheets %}
<link rel="stylesheet" type = "text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}
<br>

   <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include './storyCard.html' with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
<br>
    <h2>Other News Stories</h2>

    <div id="other-stories">
        {% if other_stories %}
            {% for story in other_stories %}
                {% include "./storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
   <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}
{% block content %}


<div id="story-wrapper">
    <h3>{{ story.title }}</h3>
    <h4>Written by <a href = "{% url 'news:author' story.author_id %}">{{ story.author }}</a><h4>
    <h6>{{ story.pub_date}}</h6>
    <br>

    <div id="story-content">
        {% if story.image %}
            <img src="{{ story.image }}">
            {% else %}
                <img src="https://picsum.photos/700">
            {% endif %}
        {{ story.content|linebreaks }}
    </div>
    <br>

    <!-- DISPLAY COMMENT SECTION -->
    <section>
        <h5>COMMENTS</h5>
<br>
    {% if story.comments.all %}
        {% for comments in story.comments.all %}
    <div class="story_comment">
        <a id="comment_author" href = "{% url 'news:author' comments.author_id %}">{{ comments.author }}</a>        
        <div class = "comment_bubble"><span id = "comment_text" class="emphasized"> {{ comments.text }} </span>
        <h6 id = "comment_date">{{ comments.date }}</h6>
        </div>
    </div>    <br>                  
        {% endfor %}
        {% else %}
            <p>There are no comments for this story..... yet.</p>
        {% endif %}
    </section>
    <br>
    <!-- ADD COMMENT SECTION -->
    <section>
        {% if request.user.is_authenticated %}
            <form method = "POST" action= "{% url 'news:addComment' story.id %}">
                {% csrf_token %}
                <h5>Join the conversation:</h5>
                {{ form.text }}
                <br>
                <input class= "hyperlink-button" type ="submit" value="Submit">
            </form>
            {% else %}
                <a class = "hyperlink-button" href="{% url 'login' %}?next={{request.path}}">Login to add a comment</a>
            {% endif %}
    </section>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{%url 'news:story' story.id %}">
        {% if story.image %}
            <img src="{{ story.image }}">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4> 
            <!-- add days / hours/ mins old -->
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static%}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Lindi">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a href="{% url 'news:index' %}" >
                    <img id = logo src="https://github.com/Lyndallh/Lyndallh.github.io/blob/main/images/ABC-logo.png?raw=true" > 
                </a>               
                <a class = "hyperlink" id="header-link" href="{% url 'news:index' %}">
                    <h1>Analytics, Bikes, Coding</h1></a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}


        </header>
        <main>
<!-- content blocks here -->
        {% block content %}{% endblock %}
    </main>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    {% if request.user.is_authenticated %}
    <a  id= "new-story" href="{% url 'news:newStory' %}">New Story</a>
    <a class = "hyperlink-button" href="{% url 'logout' %}">Logout</a>
    <a id = "nav_user" class = "hyperlink" href="{% url 'users:profile' %}"><h2>{{ user.username }}</h2></a>

    {% else %}
    <a class= "hyperlink-button" href="{% url 'login' %}">Login</a>
    <a id = "new-story" href="/users/create-account?next={{request.path}}">Sign up</a>
    <a id = "nav_user"><h2> </h2></a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}
{% block content %}


<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class = "hyperlink-button" type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends 'base.html' %}
{% block content %}

   <h2>{{ user.username }}'s News Stories</h2>

   <div id="user_stories">
    {% if user_stories %}
        {% for story in user_stories %}
        <div class="story-card">
            <a href="{%url 'news:story' story.id %}"  >
            <img src="{{ story.image }}">
            <h3 >{{story.title}}</h3>                     
            <h6> - {{ story.pub_date }}</h6>
            </a>
        </div>
        {% endfor %}
    {% else %}
        <p>No stories for {{ user.username }} yet.</p>
    {% endif %}
    </div>

<h2>{{ user.username }}'s Comments</h2>
  <div id="user_comments">
    {% if user_comments %}
        {% for comments in user_comments %}
        <div class="story_comment">
            <div class = "comment_bubble" >
                <span id="comment_text" class="emphasized"> {{ comments.text }} </span>       
                <h6 id = "comment_date"> - {{ comments.date }}</h6> 
                <a id = "story_title" href="{%url 'news:story' comments.story.id %}">
                    <h5>{{comments.story.title}}</h5>
                </a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>No comments for {{ user.username }} yet.</p>
    {% endif %}


{% endblock %}